[package]
name = "pachiri"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { version = "=0.2.2", features = ["runtime_shaders"] }
image = "0.25"
imageproc = "0.25"
global-hotkey = "0.7"
arboard = "3.6"
smallvec = "1"
ab_glyph = "0.2"
async-channel = "2"
lyon = "1"
unicode-segmentation = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
sha2 = "0.10"
hkdf = "0.12"
aes-gcm = "0.10"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2"
block = "0.1"

[dev-dependencies]
gpui = { version = "=0.2.2", features = ["test-support", "runtime_shaders"] }

[profile.release]
lto = "thin"
strip = true
